### ISSUE TITLE
SystemError: NULL result without error in PyObject_Call

### ISSUE THREAD

**Issue by quwubin** [l337x911/AmBre#4]
/usr/bif/src/primer3-2.3.0/src/primer3_core -p3_settings_file=/usr/bif/local/ActivePython-2.7/lib/python2.7/site-packages/AmBre-1.0release_r0-py2.7.egg/ambre/data/primer3_lr_A06.txt /usr/bif/ambre/tmp/GY72oW.0000.primer3
/usr/bif/src/primer3-2.3.0/src/primer3_core -p3_settings_file=/usr/bif/local/ActivePython-2.7/lib/python2.7/site-packages/AmBre-1.0release_r0-py2.7.egg/ambre/data/primer3_lr_A06.txt /usr/bif/ambre/tmp/GY72oW.0001.primer3
# Stage1 Primer3Time: 2376.0475

77972 /usr/bif/bin/blat -t=dna -q=dna -stepSize=2 -tileSize=8 -repMatch=1048576 -minScore=15 -noHead 80/ref.fa /usr/bif/ambre/tmp/GY72oW.align.fa /usr/bif/ambre/tmp/GY72oW.align.out
# Number of Primers after Blat: 73218
# Stage2 AlignTime: 372.3776
# Stage2 MultiPlxTime: 0.8981
# Number of Cross Amplifications 46840841
# Stage2 CrossAmpTime: 216.4304
# Region 0, 0-1328248 has 25224 primers
# Region 1, 1328248-3898691 has 47994 primers

/usr/bif/ambre/tmp/GY72oW.0001.primer3.out
/usr/bif/ambre/tmp/GY72oW.align.fa
/usr/bif/ambre/tmp/GY72oW.align.out
/usr/bif/ambre/tmp/GY72oW.multiplx
/usr/bif/ambre/tmp/GY72oW.multiplx.out
/usr/bif/ambre/tmp/GY72oW.sa
Traceback (most recent call last):
  File "/usr/bif/local/ActivePython-2.7/bin/ambre_design", line 9, in <module>
    load_entry_point('AmBre==1.0release-r0', 'console_scripts', 'ambre_design')()
  File "/usr/bif/local/ActivePython-2.7/lib/python2.7/site-packages/AmBre-1.0release_r0-py2.7.egg/ambre/design/workflow.py", line 746, in main
    ambre_run(args.regions[0], args.temptag, args.primer_fpath[0], fasta_flag=args.ofasta, region_links_fpath=region_links_fpath)
  File "/usr/bif/local/ActivePython-2.7/lib/python2.7/site-packages/AmBre-1.0release_r0-py2.7.egg/ambre/design/workflow.py", line 694, in ambre_run
    region_links_fpath=region_links_fpath)
  File "/usr/bif/local/ActivePython-2.7/lib/python2.7/site-packages/AmBre-1.0release_r0-py2.7.egg/ambre/design/workflow.py", line 418, in run
    output=pamp_out)
  File "/usr/bif/local/ActivePython-2.7/lib/python2.7/site-packages/AmBre-1.0release_r0-py2.7.egg/ambre/design/sa_cost.py", line 531, in multi_vary_temperature_schedule
    cost, primer_sets, iter_count, runtime = result.get()
  File "/usr/bif/local/ActivePython-2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
SystemError: NULL result without error in PyObject_Call

**Comment by anandpatel-sci** [comment]
Hello. 
What version of numpy are you using? An error in PyObject_Call typically means there is some failure in a C/C++ extension. 

The asynchronous simulated annealing calls makes it difficult to see exactly where the code is failing. I created a new branch called "sync" in the code base that will give more informative errors. The "sync" branch does not parallelize the primer selection step, and will run much slower.

**Comment by quwubin** [comment]
Solved, Thanks.
Actually, I don't know how to solved.
